/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RadioCommander */

#ifndef _Included_RadioCommander
#define _Included_RadioCommander
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MacOSX
 * Method:    getBundleNameForDevice
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kfu_Platform_MacOSX_getBundleNameForDevice
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
